# Generated by Django 3.2.5 on 2021-11-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_commentrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentrecord',
            name='videoid',
            field=models.CharField(default='INVALID_VIDEO_ID', max_length=50),
        ),
    ]
