# Generated by Django 3.2.5 on 2021-11-28 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_commentrecord_videoid'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentrecord',
            name='sentimentscore',
            field=models.FloatField(default=0.0),
        ),
    ]
