# Generated by Django 3.2.5 on 2021-12-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_commentrecord_sentimentscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentrecord',
            name='commentid',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
